<<<<<<< HEAD
# Generated by Django 3.0.4 on 2020-06-03 01:30

from django.db import migrations, models
import django.utils.timezone
=======
# Generated by Django 3.0.4 on 2020-06-03 01:45

from django.db import migrations, models
>>>>>>> ded5b369557e236f11f16c900ca6e031a5e6918d


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
<<<<<<< HEAD
            field=models.PositiveIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
=======
            field=models.PositiveIntegerField(default=10),
>>>>>>> ded5b369557e236f11f16c900ca6e031a5e6918d
        ),
    ]
