# Generated by Django 3.0.4 on 2020-06-03 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
    ]
