export const EVENT_USER_ADDED_STARTED = 'EVENT_USER_ADDED_STARTED';
export const EVENT_USER_ADDED_COMPLETED = 'EVENT_USER_ADDED_COMPLETED';
export const EVENT_USER_ADDED_FAILED = 'EVENT_USER_ADDED_FAILED';

export const EVENT_USER_REMOVED_STARTED = 'EVENT_USER_REMOVED_STARTED';
export const EVENT_USER_REMOVED_COMPLETED = 'EVENT_USER_REMOVED_COMPLETED';
export const EVENT_USER_REMOVED_FAILED = 'EVENT_USER_REMOVED_FAILED';

export const EVENTS_USERS_FETCH_COMPLETED = 'EVENTS_USERS_FETCH_COMPLETED';
export const EVENTS_USERS_FETCH_STARTED = 'EVENTS_USERS_FETCH_STARTED';
export const EVENTS_USERS_FETCH_FAILED = 'EVENTS_USERS_FETCH_FAILED';
