export const EVENT_ADDED_STARTED = 'EVENT_ADDED_STARTED';
export const EVENT_ADDED_COMPLETED = 'EVENT_ADDED_COMPLETED';
export const EVENT_ADDED_FAILED = 'EVENT_ADDED_FAILED';

export const EVENT_REMOVED_STARTED = 'EVENT_REMOVED_STARTED';
export const EVENT_REMOVED_COMPLETED = 'EVENT_REMOVED_COMPLETED';
export const EVENT_REMOVED_FAILED = 'EVENT_REMOVED_FAILED';

export const EVENTS_FETCH_COMPLETED = 'EVENTS_FETCH_COMPLETED';
export const EVENTS_FETCH_STARTED = 'EVENTS_FETCH_STARTED';
export const EVENTS_FETCH_FAILED = 'EVENT_FETCH_FAILED';

