# Generated by Django 3.0.4 on 2020-06-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='user',
            new_name='user_id',
        ),
    ]
