# Generated by Django 3.0.4 on 2020-06-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200601_0152'),
        ('users', '0004_auto_20200530_2227'),
    ]

    operations = [
    ]
