export const TUTOR_ADDED_STARTED = 'TUTOR_ADDED_STARTED';
export const TUTOR_ADDED_COMPLETED = 'TUTOR_ADDED_COMPLETED';
export const TUTOR_ADDED_FAILED = 'TUTOR_ADDED_FAILED';

export const TUTOR_REMOVED_STARTED = 'TUTOR_REMOVED_STARTED';
export const TUTOR_REMOVED_COMPLETED = 'TUTOR_REMOVED_COMPLETED';
export const TUTOR_REMOVED_FAILED = 'TUTOR_REMOVED_FAILED';

export const TUTORS_FETCH_COMPLETED = 'TUTORS_FETCH_COMPLETED';
export const TUTORS_FETCH_STARTED = 'TUTORS_FETCH_STARTED';
export const TUTORS_FETCH_FAILED = 'TUTORS_FETCH_FAILED';