export const USER_ADDED_STARTED = 'USER_ADDED_STARTED';
export const USER_ADDED_COMPLETED = 'USER_ADDED_COMPLETED';
export const USER_ADDED_FAILED = 'USER_ADDED_FAILED';

export const USER_REMOVED_STARTED = 'USER_REMOVED_STARTED';
export const USER_REMOVED_COMPLETED = 'USER_REMOVED_COMPLETED';
export const USER_REMOVED_FAILED = 'USER_REMOVED_FAILED';

export const USERS_FETCH_COMPLETED = 'USERS_FETCH_COMPLETED';
export const USERS_FETCH_STARTED = 'USERS_FETCH_STARTED';
export const USERS_FETCH_FAILED = 'USERS_FETCH_FAILED';